version: "3.8"

services:
  seller-platform-backend:
    image: seller-platform-backend:latest
    container_name: seller-platform-backend
    restart: always
    ports:
      - "9000:9000"
    env_file:
      - /home/ubuntu/seller-platform-backend/.env
    volumes:
      - /home/ubuntu/seller-platform-backend:/usr/src/app
